/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoescuela;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;

import javax.swing.JOptionPane;

/**
 *
 * @author equipo
 */
public class FormularioClienteEstudiante extends javax.swing.JFrame {

        private static final String SERVER_IP = "127.0.0.1";
        private static final int SERVER_PORT = 12345;
        private Socket socket;
        private DataInputStream input;
        private DataOutputStream output;

        /**
         * Creates new form FormularioClienteEstudiante
         */
        public FormularioClienteEstudiante() {
                initComponents();
                abrirConexionConElServidor();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lbInstruccion1 = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                lbMatricula = new javax.swing.JLabel();
                lbSemestre = new javax.swing.JLabel();
                lbCarrera = new javax.swing.JLabel();
                lbActividad1 = new javax.swing.JLabel();
                lbActividad2 = new javax.swing.JLabel();
                txtNombre = new javax.swing.JTextField();
                txtMatricula = new javax.swing.JTextField();
                comboSemestre = new javax.swing.JComboBox<>();
                comboCarrera = new javax.swing.JComboBox<>();
                comboActividad1 = new javax.swing.JComboBox<>();
                comboActividad2 = new javax.swing.JComboBox<>();
                btnEnviar = new javax.swing.JButton();
                lbInstruccion2 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();
                jScrollPane1 = new javax.swing.JScrollPane();
                TextAreaInformacion1 = new javax.swing.JTextArea();
                btnImprimir = new javax.swing.JButton();
                btnSalir = new javax.swing.JButton();
                btnLimpiar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Cliente");

                lbInstruccion1.setText("1. Ingresa los datos del estudiante");

                lbNombre.setText("Nombre del estudiante");

                lbMatricula.setText("Matricula");

                lbSemestre.setText("Semestre");

                lbCarrera.setText("Carrera");

                lbActividad1.setText("Actividad extracurricular 1");

                lbActividad2.setText("Actividad extracurricular 2");

                comboSemestre.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "1er semestre", "2do semestre",
                                                "3er semestre", "4to semestre", "5to semestre", "6to semestre",
                                                "7mo semestre", "8vo semestre" }));

                comboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Biotecnología", "Desarrollo de Software", "Energías Renovables",
                                                "Gestión Industrial",
                                                "Logística y Transporte", "Tecnología Ambiental", "Telemática" }));

                comboActividad1.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Fútbol", "Voleibol", "Básquetbol", "Taekwondo" }));

                comboActividad2.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Taller de fotografía digital",
                                                "Curso de programación web", "Curso de programación móvil" }));

                btnEnviar.setText("Enviar");
                btnEnviar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEnviarActionPerformed(evt);
                        }
                });

                lbInstruccion2.setText("3. Recibe respuesta de la Universidad");

                TextAreaInformacion1.setColumns(20);
                TextAreaInformacion1.setRows(5);
                jScrollPane1.setViewportView(TextAreaInformacion1);

                btnImprimir.setText("Imprimir");
                btnImprimir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnImprimirActionPerformed(evt);
                        }
                });

                btnSalir.setText("Salir");
                btnSalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSalirActionPerformed(evt);
                        }
                });

                btnLimpiar.setText("Limpiar campos");
                btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLimpiarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(lbInstruccion1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jSeparator1))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(btnSalir)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(btnImprimir))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(lbInstruccion2)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(jSeparator2))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(lbNombre)
                                                                                                                                                                .addComponent(lbMatricula)
                                                                                                                                                                .addComponent(lbActividad1)
                                                                                                                                                                .addComponent(lbActividad2)
                                                                                                                                                                .addComponent(lbSemestre)
                                                                                                                                                                .addComponent(lbCarrera))
                                                                                                                                                .addGap(28, 28, 28)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(comboActividad2,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(comboActividad1,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(txtNombre,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                246,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(txtMatricula,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                246,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(comboSemestre,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(comboCarrera,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                429,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 24, Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(btnLimpiar)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnEnviar)
                                                                                                .addGap(49, 49, 49)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(lbInstruccion1)
                                                                                .addComponent(jSeparator1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                10,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lbNombre)
                                                                                .addComponent(txtNombre,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lbMatricula)
                                                                                .addComponent(txtMatricula,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(comboCarrera,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lbCarrera))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(lbSemestre)
                                                                                                .addGap(26, 26, 26)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lbActividad1)
                                                                                                                .addComponent(comboActividad1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(comboActividad2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(lbActividad2))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                8,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnLimpiar)
                                                                                                                .addComponent(btnEnviar))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lbInstruccion2,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jSeparator2,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                10,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(27, 27, 27)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                235,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnImprimir)
                                                                                                                .addComponent(btnSalir))
                                                                                                .addGap(21, 21, 21))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(comboSemestre,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // -->>DE CLIENTE A SERVIDOR (OUTPUT)
        // Método para abrir una conexión con el servidor a través de sockets.
        private void abrirConexionConElServidor() {
                String msg = null;
                String ip = null;
                int puerto = 0;
                try {
                        ip = SERVER_IP;
                        puerto = SERVER_PORT;
                        socket = new Socket(ip, puerto);
                        output = new DataOutputStream(socket.getOutputStream());
                        input = new DataInputStream(socket.getInputStream());
                } catch (IOException e) {
                        msg = "Error al intentar abrir la conexión con el servidor.\n"
                                        + "Ip: " + ip + "\nPuerto: " + puerto
                                        + "\n\nProbablemente el servidor no está disponible o el puerto está en uso.";
                        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();
                }
        }

        // Método para enviar solictudes de estudiantes
        private void enviarDatos() {
                try {
                        // Recuperar datos del formulario
                        String nombre = txtNombre.getText();
                        String matricula = txtMatricula.getText();
                        // Validar que los campos de nombre y matrícula no estén vacíos
                        if (nombre.isEmpty() || matricula.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre y la matrícula.",
                                                "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return; // Salir del método si la validación falla
                        }
                        // Recupera los datos del formulario cliente
                        String semestre = comboSemestre.getSelectedItem().toString();
                        String carrera = comboCarrera.getSelectedItem().toString();
                        String deporteSeleccionado = comboActividad1.getSelectedItem().toString();
                        String tallerCursoSeleccionado = comboActividad2.getSelectedItem().toString();
                        // Crear objeto SolicitudEstudiante
                        SolicitudEstudiante solicitud = new SolicitudEstudiante(nombre, matricula, semestre, carrera,
                                        deporteSeleccionado, tallerCursoSeleccionado);
                        // Enviar objeto al servidor
                        try (ObjectOutputStream objectOutput = new ObjectOutputStream(output)) {
                                objectOutput.writeObject(solicitud);
                                objectOutput.flush();
                        }
                        JOptionPane.showMessageDialog(this, "Datos enviados correctamente al servidor.", "Éxito",
                                        JOptionPane.INFORMATION_MESSAGE);
                        abrirConexionConElServidor();
                        iniciarEscuchaServidor();
                } catch (IOException | NullPointerException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Error al enviar los datos al servidor.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        // <<--DE SERVIDOR A CLIENTE (INPUT)
        // Clase interna quie implementa un método para recibir objetos del servidor y
        // procesarlos
        private class EscucharServidor extends Thread {

                @Override
                public void run() {
                        try {
                                while (true) {
                                        String mensaje = input.readUTF();
                                        // Mostrar la información recibida en TextAreaInformacion1
                                        TextAreaInformacion1.append(mensaje);
                                }
                        } catch (IOException e) {
                                e.printStackTrace();
                        }
                }
        }

        private void iniciarEscuchaServidor() {
                EscucharServidor escucharServidor = new EscucharServidor();
                escucharServidor.start();
        }

        // METODOS PARA LA GUI
        // 1. Salir de la aplicacion
        private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
                this.dispose();
        }// GEN-LAST:event_btnSalirActionPerformed

        // 2. Limpiar campos del formulario
        private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarActionPerformed
                limpiarCampos();
        }// GEN-LAST:event_btnLimpiarActionPerformed
         // 3. Enviar la informacion al FormularioServidorEscuela

        private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnviarActionPerformed
                enviarDatos();
        }// GEN-LAST:event_btnEnviarActionPerformed

        // 4. Genera la información recibida del FormularioServidorEscuela en el
        // TextAreaInformacion en un archivo de texto.
        private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnImprimirActionPerformed
                // Obtener los datos del formulario
                String nombre = txtNombre.getText();
                String matricula = txtMatricula.getText();
                String semestre = comboSemestre.getSelectedItem().toString();
                String carrera = comboCarrera.getSelectedItem().toString();
                String actividad1 = comboActividad1.getSelectedItem().toString();
                String actividad2 = comboActividad2.getSelectedItem().toString();

                // Crear la cadena de la solicitud
                StringBuilder solicitud = new StringBuilder();
                solicitud.append(">>>>>>>>DATOS DE MI SOLICITUD>>>>>>>>>>>>>>>> ").append("\n");
                solicitud.append("Nombre: ").append(nombre).append("\n");
                solicitud.append("Matrícula: ").append(matricula).append("\n");
                solicitud.append("Semestre: ").append(semestre).append("\n");
                solicitud.append("Carrera: ").append(carrera).append("\n");
                solicitud.append("Actividad 1: ").append(actividad1).append("\n");
                solicitud.append("Actividad 2: ").append(actividad2).append("\n");
                solicitud.append("-----------------------------------------------------------------------")
                                .append("\n");

                // Imprimir la solicitud en TextAreaInformacion1
                TextAreaInformacion1.setText(solicitud.toString());
        }// GEN-LAST:event_btnImprimirActionPerformed

        private void limpiarCampos() {
                txtNombre.setText("");
                txtMatricula.setText("");
                comboSemestre.setSelectedIndex(0);
                comboCarrera.setSelectedIndex(0);
                comboActividad1.setSelectedIndex(0);
                comboActividad2.setSelectedIndex(0);
                TextAreaInformacion1.setText("");
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FormularioClienteEstudiante.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FormularioClienteEstudiante.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FormularioClienteEstudiante.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FormularioClienteEstudiante.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FormularioClienteEstudiante().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextArea TextAreaInformacion1;
        private javax.swing.JButton btnEnviar;
        private javax.swing.JButton btnImprimir;
        private javax.swing.JButton btnLimpiar;
        private javax.swing.JButton btnSalir;
        private javax.swing.JComboBox<String> comboActividad1;
        private javax.swing.JComboBox<String> comboActividad2;
        private javax.swing.JComboBox<String> comboCarrera;
        private javax.swing.JComboBox<String> comboSemestre;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lbActividad1;
        private javax.swing.JLabel lbActividad2;
        private javax.swing.JLabel lbCarrera;
        private javax.swing.JLabel lbInstruccion1;
        private javax.swing.JLabel lbInstruccion2;
        private javax.swing.JLabel lbMatricula;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbSemestre;
        private javax.swing.JTextField txtMatricula;
        private javax.swing.JTextField txtNombre;
        // End of variables declaration//GEN-END:variables
}
