/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoescuela;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.ServerSocket;
import java.net.Socket;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author equipo
 */
public class FormularioServidorEscuela extends javax.swing.JFrame {

    private static final String SERVER_IP = "127.0.0.1";
    private static final int SERVER_PORT = 12345;

    private ServerSocket serverSocket;// Se utiliza para esperar las conexiones entrantes de los clientes.
    private Socket clientSocket;// se utiliza para almacenar la instancia de Socket que representa la conexión
                                // con un cliente específico.
    private DataInputStream input;// se utiliza para leer datos del cliente a través de la conexión establecida.
    private DataOutputStream output;// se utiliza para enviar datos al cliente a través de la conexión establecida.
    private int contadorSolicitudes = 0;

    /**
     * Creates new form FormularioServidorEscuela
     */
    public FormularioServidorEscuela() {
        initComponents();
        abrirSocket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaInformacion2 = new javax.swing.JTextArea();
        lbInstruccion3 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");

        TextAreaInformacion2.setColumns(20);
        TextAreaInformacion2.setRows(5);
        jScrollPane1.setViewportView(TextAreaInformacion2);

        lbInstruccion3.setText("2.Recibe solicitudes de los estudiantes y asigna horarios");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar campo");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSalir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLimpiar)
                                                .addGap(27, 27, 27)
                                                .addComponent(btnEnviar))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbInstruccion3)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(35, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lbInstruccion3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(btnSalir))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnEnviar)
                                                        .addComponent(btnLimpiar))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // -->> DE CLIENTE A SERVIDOR (INPUT)
    private void abrirSocket() {
        SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() throws Exception {
                String msg = null;
                try {
                    int puerto = SERVER_PORT;
                    serverSocket = new ServerSocket(puerto);
                    clientSocket = serverSocket.accept();
                    // Configura flujos de entrada y salida
                    input = new DataInputStream(clientSocket.getInputStream());
                    output = new DataOutputStream(clientSocket.getOutputStream());
                    // Inicia la lectura de datos del cliente en un hilo separado
                    iniciarEscuchaCliente();
                } catch (IOException e) {
                    msg = "Error al intentar abrir socket en el puerto " + SERVER_PORT + "\n\n"
                            + "Probablemente el puerto esté en uso o el firewall "
                            + "de su equipo impidió su apertura.";
                    publish(msg);
                } finally {
                    // Cierra el socket del servidor
                    if (serverSocket != null && !serverSocket.isClosed()) {
                        try {
                            serverSocket.close();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                    }
                }
                return null;
            }

            @Override
            protected void process(java.util.List<String> chunks) {
                // Actualiza la interfaz de usuario con mensajes de progreso o resultados
                for (String msg : chunks) {
                    JOptionPane.showMessageDialog(FormularioServidorEscuela.this, msg, "Información",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
        };
        worker.execute();
    }

    // Método para mostrar información del cliente en TextAreaInformacion2
    private void mostrarInformacionCliente(SolicitudEstudiante solicitud) {
        // Incrementar el contador de solicitudes
        contadorSolicitudes++;
        // Mostrar la información del cliente en TextAreaInformacion2
        String infoCliente = ">>>>>DATOS DEL ESTUDIANTE>>>>>>>>>>"
                + "\nSolicitud número: " + contadorSolicitudes
                + "\nNombre: " + solicitud.getNombre()
                + "\nMatrícula: " + solicitud.getMatricula()
                + "\nSemestre: " + solicitud.getSemestre()
                + "\nCarrera: " + solicitud.getCarrera()
                + "\nDeporte: " + solicitud.getDeporteSeleccionado()
                + "\nTaller/Curso: " + solicitud.getTallerCursoSeleccionado()
                + "\n"
                + "\n>>>>>ASIGNACION DE HORARIOS>>>>>>>>>>>>>>>>> "
                + "\nDeporte: Lunes a Viernes. De _ a _"
                + "\nTaller/Curso: Lunes a Viernes. De _ a _"
                + "\n-----------------------------------------------------------------------------------\n";
        TextAreaInformacion2.append(infoCliente);
    }

    // Clase interna quie implementa un método para recibir solicitudes del cliente
    // y procesarlos
    private class EscucharCliente extends Thread {
        @Override
        public void run() {
            try {
                ObjectInputStream objectInput = new ObjectInputStream(clientSocket.getInputStream());
                while (true) {
                    try {
                        Object obj = objectInput.readObject();
                        if (obj instanceof SolicitudEstudiante) {
                            // Procesar la solicitud
                            SolicitudEstudiante solicitud = (SolicitudEstudiante) obj;
                            mostrarInformacionCliente(solicitud);
                            abrirSocket();
                        }
                    } catch (EOFException e) {
                        // El cliente cerró la conexión
                        break;
                    }
                }
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

    // Metodo auxiliar para escuchar al cliente
    private void iniciarEscuchaCliente() {
        EscucharCliente escucharServidor = new EscucharCliente();
        escucharServidor.start();
    }

    // <<-- DE SERVIDOR A CLIENTE (OUTPUT)
    private void enviarDatosAlCliente(String informacion) {
        try {
            // Enviar información al cliente
            output.writeUTF(informacion);
            output.writeInt(contadorSolicitudes); // Envía el contador de solicitudes al cliente
            output.flush();
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al enviar datos al cliente.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // METODOS PARA LA GUI
    // 1. Salir
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnSalirActionPerformed

    // 2. Botón enviar respuesta. Envía la información que se encuentra en el
    // TextAreaInformacion y el horario de las actividades extracurriculares.
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener información del TextAreaInformacion2
        String informacion = TextAreaInformacion2.getText();
        // Enviar la información al cliente
        enviarDatosAlCliente(informacion);
    }

    // 3. Limpiar campos
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }

    private void limpiarCampos() {
        TextAreaInformacion2.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioServidorEscuela.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioServidorEscuela.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioServidorEscuela.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioServidorEscuela.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioServidorEscuela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaInformacion2;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbInstruccion3;
    // End of variables declaration//GEN-END:variables
}
